import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App';
import Compare from './Compare';
import './styles.css';
import './practice.css';
const path = window.location.pathname.replace(/\/+$/, '') || '/';
const practice = path === '/practice';
document.title = path === '/compare' ? 'Hatch · Detail comparison' : practice ? 'Hatch · Practice copy' : 'Hatch · Discovery';
ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode>{path === '/compare' ? <Compare /> : <App practice={practice} />}</React.StrictMode>);
